### ISSUE TITLE
Explain why OccurenceOrderPlugin

### ISSUE THREAD

**Issue by TheLarkInn** [styopdev/webpack-interview-questions#2]
Good q: 

Why is OccourenceOrderPlugin a size optimization?😉 It has to do with module ids and topological sorting.

**Comment by styopdev** [comment]
Great, thanks

What about more formal version?

q: Why the OccurenceOrderPlugin is the part of webpack optimisation. What it has to do with module ids and topological sorting?

a: OccurenceOrderPlugin order the modules and chunks by occurrence. More module occurs - smaller id it has, this technique helps to reduce bundle size.

**Comment by TheLarkInn** [comment]
Exactlyyyyyyyyyyyy!!!! 👏👏👏👏

**Comment by TheLarkInn** [comment]
I might elaborate and say because a module is used many times it will be referenced many times with __webpack_require__(moduleId)

**Comment by styopdev** [comment]
Added - https://github.com/styopdev/webpack-interview-questions/commit/494b3d56954588a0e48f701d0286e16fbb33f940
